CUSTOMER_LIST = [{
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rh",
                            "name":"Abel aaberg",
                            "email_id": "abelaaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"

                            
                        },
                        {
                            "cdp_id": "cdp-1234322",
                            "sfsc_id":"2873ghr87938ri",
                            "name":"Abel aberg",
                            "email_id": "abelaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234324",
                            "sfsc_id":"2873ghr87938rg",
                            "name":"Abel acker",
                            "email_id": "abelackerg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                           "cdp_id": "cdp-1234325",
                            "sfsc_id":"2873ghr87938rk",
                            "name":"Abel adam",
                            "email_id": "abeladam@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938ra",
                            "name":"Abel adame",
                            "email_id": "abeladame@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343215",
                            "sfsc_id":"2873ghr87938rb",
                            "name":"Abel adames",
                            "email_id": "abeladames@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938rc",
                            "name":"Abel adamest",
                            "email_id": "abeladamest@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343219",
                            "sfsc_id":"2873ghr87938rd",
                            "name":"Abel adameste",
                            "email_id": "abeladameste@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                            
                        },
                        {
                            "cdp_id": "cdp-12343218",
                            "sfsc_id":"2873ghr87938re",
                            "name":"Abel adamester",
                            "email_id": "abeladamester@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rf",
                            "name":"Abel adamez",
                            "email_id": "abeladamez@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rh",
                            "name":"Abel aaberg",
                            "email_id": "abelaaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"

                            
                        },
                        {
                            "cdp_id": "cdp-1234322",
                            "sfsc_id":"2873ghr87938ri",
                            "name":"Abel aberg",
                            "email_id": "abelaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234324",
                            "sfsc_id":"2873ghr87938rg",
                            "name":"Abel acker",
                            "email_id": "abelackerg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                           "cdp_id": "cdp-1234325",
                            "sfsc_id":"2873ghr87938rk",
                            "name":"Abel adam",
                            "email_id": "abeladam@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938ra",
                            "name":"Abel adame",
                            "email_id": "abeladame@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343215",
                            "sfsc_id":"2873ghr87938rb",
                            "name":"Abel adames",
                            "email_id": "abeladames@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938rc",
                            "name":"Abel adamest",
                            "email_id": "abeladamest@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343219",
                            "sfsc_id":"2873ghr87938rd",
                            "name":"Abel adameste",
                            "email_id": "abeladameste@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                            
                        },
                        {
                            "cdp_id": "cdp-12343218",
                            "sfsc_id":"2873ghr87938re",
                            "name":"Abel adamester",
                            "email_id": "abeladamester@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rf",
                            "name":"Abel adamez",
                            "email_id": "abeladamez@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rh",
                            "name":"Abel aaberg",
                            "email_id": "abelaaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"

                            
                        },
                        {
                            "cdp_id": "cdp-1234322",
                            "sfsc_id":"2873ghr87938ri",
                            "name":"Abel aberg",
                            "email_id": "abelaberg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234324",
                            "sfsc_id":"2873ghr87938rg",
                            "name":"Abel acker",
                            "email_id": "abelackerg@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                           "cdp_id": "cdp-1234325",
                            "sfsc_id":"2873ghr87938rk",
                            "name":"Abel adam",
                            "email_id": "abeladam@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938ra",
                            "name":"Abel adame",
                            "email_id": "abeladame@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343215",
                            "sfsc_id":"2873ghr87938rb",
                            "name":"Abel adames",
                            "email_id": "abeladames@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"Saudi Arabia",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343217",
                            "sfsc_id":"2873ghr87938rc",
                            "name":"Abel adamest",
                            "email_id": "abeladamest@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-12343219",
                            "sfsc_id":"2873ghr87938rd",
                            "name":"Abel adameste",
                            "email_id": "abeladameste@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                            
                        },
                        {
                            "cdp_id": "cdp-12343218",
                            "sfsc_id":"2873ghr87938re",
                            "name":"Abel adamester",
                            "email_id": "abeladamester@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        },
                        {
                            "cdp_id": "cdp-1234321",
                            "sfsc_id":"2873ghr87938rf",
                            "name":"Abel adamez",
                            "email_id": "abeladamez@gmail.com",
                            "mobile_no":"8888812344",
                            "country":"United Arab Emirates",
                            "city":"Sharjah",
                            "country_code":"AE",
                            "postal_code":"1234",
                            "card_no":"12345",
                            "user_id":"3453",
                            "gender":"male",
                            "phone_code":"971",
                            "block":"5",
                            "account_no":"8798",
                            "pan_no":"732"
                        }]

CUSTOMER_LIST_KEYS = [
                        "cdp_id",
                        "sfsc_id",
                        "name",
                        "email_id",
                        "mobile_no",
                        "country",
                        "city",
                        "country_code",
                        "postal_code",
                        "card_no",
                        "user_id",
                        "gender",
                        "phone_code",
                        "block",
                        "account_no",
                        "pan_no"
                        ]